version: '3.4'
services:
  miniflux:
    image: miniflux/miniflux:2.0.36
    container_name: miniflux
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
        #- RUN_MIGRATIONS=1
        #- CREATE_ADMIN=1
        #- ADMIN_USERNAME=admin
        #- ADMIN_PASSWORD=password
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
  db:
    image: postgres:14.2
    container_name: miniflux_db
      # environment:
      #   - POSTGRES_USER=miniflux
      #   - POSTGRES_PASSWORD=secret
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
volumes:
  miniflux-db:
