version: '3'

services:
  app:
    image: enterhaken/storm:${VERSION:-latest}
    container_name: storm_app
    restart: always
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-localhost}
      - POSTGRES_DB=${POSTGRES_DB:-postgres_prod}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${APP_PORT:-4000}:4000"
    depends_on:
      - db

  db:
    image: postgres:13.1
    container_name: storm_postgres_prod
    restart: always
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-localhost}
      - POSTGRES_DB=${POSTGRES_DB:-postgres_prod}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    # init db script will be only executed 
    # when the container runs the first time
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db:

