version: '2'
services:
  web:
    image: odoo:14.0
    depends_on:
     - db
    ports:
      - "8069:${ODOO_PORT:-8069}"
    environment:
      - USER=${ODOO_USER:-odoo}
      - PASSWORD=${ODOO_PASSWORD:-password}
  db:
    image: postgres:13.3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${ODOO_PASSWORD:-password}
      - POSTGRES_USER=${ODOO_USER:-odoo}
